server:
  port: 8090
spring:
  application:
    name: task_tracker
    version: 0.0.1-SNAPSHOT
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5436/task_tracker_db}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db.changelog/changelog-master.yaml
    enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect